### ISSUE TITLE
1.18.1 forge crash

### ISSUE THREAD

**Issue by Pokrzywnik** [PssbleTrngle/Skygrid#40]
My game crashes after installing newest 1.18.1 version (skygrid-forge-3.0.1-alpha.jar) and 1.18.1 version of kotlin for forge (kotlinforforge-3.0.0-obf.jar)

> [20:47:07] [main/INFO]: ModLauncher running: args [--username, Frodo, --version, Forge 1.18.1, --gameDir, C:\Users\Mateusz\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Mateusz\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, 735304b81e044f2aa8cf04b58b8fa833, --accessToken, вќ„вќ„вќ„вќ„вќ„вќ„вќ„вќ„, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, modified, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 39.0.88, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[20:47:07] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.1 by Microsoft
[20:47:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Mateusz/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=CLIENT
[20:47:42] [main/INFO]: Found mod file kotlinforforge-3.0.0-obf.jar of type LANGPROVIDER with locator {mods folder locator at C:\Users\Mateusz\AppData\Roaming\.minecraft\mods}
[20:47:42] [main/INFO]: Found mod file skygrid-forge-3.0.1-alpha.jar of type MOD with locator {mods folder locator at C:\Users\Mateusz\AppData\Roaming\.minecraft\mods}
[20:47:62] [main/INFO]: Found mod file fmlcore-1.18.1-39.0.88.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4d4d8fcf
[20:47:63] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.0.88.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4d4d8fcf
[20:47:63] [main/INFO]: Found mod file mclanguage-1.18.1-39.0.88.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4d4d8fcf
[20:47:63] [main/INFO]: Found mod file client-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4d4d8fcf
[20:47:63] [main/INFO]: Found mod file forge-1.18.1-39.0.88-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@4d4d8fcf
2022-03-11 20:47:08,751 main WARN Error parsing URI C:\Users\Mateusz\AppData\Roaming\.minecraft\assets\log_configs\client-1.12.xml
Exception in thread "main" java.lang.module.ResolutionException: Modules kotlinforforge.obf and skygrid export package kotlin.reflect.jvm.internal.impl.serialization.deserialization.builtins to module forge
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (34 ms)

**Comment by PssbleTrngle** [comment]
Seems like I got something mixed up in the build process, there will be a fix out shortly

**Comment by PssbleTrngle** [comment]
Version 3.0.2 should fix this issue, fell free to re-open otherwise
